# Add the 'vk_queue' library target
# add_library(vk_queue_lib STATIC vk_queue.cpp)
# target_compile_features(vk_queue_lib PRIVATE cxx_std_20)
# target_include_directories(
#   vk_queue_lib
#   PRIVATE
#   ${VK_COMMON_INCLUDE_DIRS}
# )
# target_link_libraries(
#   vk_queue_lib 
#   PRIVATE 
#   ${VK_COMMON_LIBS}
# )
