
##########################################
###### Add Subdirectories ################
##########################################
add_subdirectory(engine)
add_subdirectory(serializer)
add_subdirectory(types)
add_subdirectory(utils)
add_subdirectory(uuid)
##########################################
##########################################
