########### AGGREGATED COMPONENTS AND DEPENDENCIES FOR THE MULTI CONFIG #####################
#############################################################################################

list(APPEND ktx_COMPONENT_NAMES KTX::ktx)
list(REMOVE_DUPLICATES ktx_COMPONENT_NAMES)
list(APPEND ktx_FIND_DEPENDENCY_NAMES zstd)
list(REMOVE_DUPLICATES ktx_FIND_DEPENDENCY_NAMES)
set(zstd_FIND_MODE "NO_MODULE")

########### VARIABLES #######################################################################
#############################################################################################
set(ktx_PACKAGE_FOLDER_DEBUG "C:/Users/ga1ox/.conan2/p/b/ktxefb1154ac79d7/p")
set(ktx_BUILD_MODULES_PATHS_DEBUG )


set(ktx_INCLUDE_DIRS_DEBUG "${ktx_PACKAGE_FOLDER_DEBUG}/include")
set(ktx_RES_DIRS_DEBUG )
set(ktx_DEFINITIONS_DEBUG "-DKTX_FEATURE_KTX1"
			"-DKTX_FEATURE_KTX2"
			"-DKTX_FEATURE_WRITE"
			"-DKHRONOS_STATIC"
			"-DBASISU_NO_ITERATOR_DEBUG_LEVEL")
set(ktx_SHARED_LINK_FLAGS_DEBUG )
set(ktx_EXE_LINK_FLAGS_DEBUG )
set(ktx_OBJECTS_DEBUG )
set(ktx_COMPILE_DEFINITIONS_DEBUG "KTX_FEATURE_KTX1"
			"KTX_FEATURE_KTX2"
			"KTX_FEATURE_WRITE"
			"KHRONOS_STATIC"
			"BASISU_NO_ITERATOR_DEBUG_LEVEL")
set(ktx_COMPILE_OPTIONS_C_DEBUG )
set(ktx_COMPILE_OPTIONS_CXX_DEBUG )
set(ktx_LIB_DIRS_DEBUG "${ktx_PACKAGE_FOLDER_DEBUG}/lib")
set(ktx_BIN_DIRS_DEBUG )
set(ktx_LIBRARY_TYPE_DEBUG STATIC)
set(ktx_IS_HOST_WINDOWS_DEBUG 1)
set(ktx_LIBS_DEBUG ktx)
set(ktx_SYSTEM_LIBS_DEBUG )
set(ktx_FRAMEWORK_DIRS_DEBUG )
set(ktx_FRAMEWORKS_DEBUG )
set(ktx_BUILD_DIRS_DEBUG )
set(ktx_NO_SONAME_MODE_DEBUG FALSE)


# COMPOUND VARIABLES
set(ktx_COMPILE_OPTIONS_DEBUG
    "$<$<COMPILE_LANGUAGE:CXX>:${ktx_COMPILE_OPTIONS_CXX_DEBUG}>"
    "$<$<COMPILE_LANGUAGE:C>:${ktx_COMPILE_OPTIONS_C_DEBUG}>")
set(ktx_LINKER_FLAGS_DEBUG
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${ktx_SHARED_LINK_FLAGS_DEBUG}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${ktx_SHARED_LINK_FLAGS_DEBUG}>"
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${ktx_EXE_LINK_FLAGS_DEBUG}>")


set(ktx_COMPONENTS_DEBUG KTX::ktx)
########### COMPONENT KTX::ktx VARIABLES ############################################

set(ktx_KTX_ktx_INCLUDE_DIRS_DEBUG "${ktx_PACKAGE_FOLDER_DEBUG}/include")
set(ktx_KTX_ktx_LIB_DIRS_DEBUG "${ktx_PACKAGE_FOLDER_DEBUG}/lib")
set(ktx_KTX_ktx_BIN_DIRS_DEBUG )
set(ktx_KTX_ktx_LIBRARY_TYPE_DEBUG STATIC)
set(ktx_KTX_ktx_IS_HOST_WINDOWS_DEBUG 1)
set(ktx_KTX_ktx_RES_DIRS_DEBUG )
set(ktx_KTX_ktx_DEFINITIONS_DEBUG "-DKTX_FEATURE_KTX1"
			"-DKTX_FEATURE_KTX2"
			"-DKTX_FEATURE_WRITE"
			"-DKHRONOS_STATIC"
			"-DBASISU_NO_ITERATOR_DEBUG_LEVEL")
set(ktx_KTX_ktx_OBJECTS_DEBUG )
set(ktx_KTX_ktx_COMPILE_DEFINITIONS_DEBUG "KTX_FEATURE_KTX1"
			"KTX_FEATURE_KTX2"
			"KTX_FEATURE_WRITE"
			"KHRONOS_STATIC"
			"BASISU_NO_ITERATOR_DEBUG_LEVEL")
set(ktx_KTX_ktx_COMPILE_OPTIONS_C_DEBUG "")
set(ktx_KTX_ktx_COMPILE_OPTIONS_CXX_DEBUG "")
set(ktx_KTX_ktx_LIBS_DEBUG ktx)
set(ktx_KTX_ktx_SYSTEM_LIBS_DEBUG )
set(ktx_KTX_ktx_FRAMEWORK_DIRS_DEBUG )
set(ktx_KTX_ktx_FRAMEWORKS_DEBUG )
set(ktx_KTX_ktx_DEPENDENCIES_DEBUG zstd::libzstd_static)
set(ktx_KTX_ktx_SHARED_LINK_FLAGS_DEBUG )
set(ktx_KTX_ktx_EXE_LINK_FLAGS_DEBUG )
set(ktx_KTX_ktx_NO_SONAME_MODE_DEBUG FALSE)

# COMPOUND VARIABLES
set(ktx_KTX_ktx_LINKER_FLAGS_DEBUG
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:${ktx_KTX_ktx_SHARED_LINK_FLAGS_DEBUG}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:${ktx_KTX_ktx_SHARED_LINK_FLAGS_DEBUG}>
        $<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:${ktx_KTX_ktx_EXE_LINK_FLAGS_DEBUG}>
)
set(ktx_KTX_ktx_COMPILE_OPTIONS_DEBUG
    "$<$<COMPILE_LANGUAGE:CXX>:${ktx_KTX_ktx_COMPILE_OPTIONS_CXX_DEBUG}>"
    "$<$<COMPILE_LANGUAGE:C>:${ktx_KTX_ktx_COMPILE_OPTIONS_C_DEBUG}>")